server.port: 8787

solon.app:
  name: 'UsagiCardAdapter'
  group: 'UsagiCard'
solon:
  threads:
    virtual:
      enabled: true
  serialization.json:
    nullAsWriteable: true

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
app:
  usagi:
    fish:
      uuid-mapping-file-path: data/usagi_fish_mapping.json
    dev-token: ${USAGI_DEV_TOKEN}
    version-file-path: data/versions.json
